version: "3.9"

services:
  mongodb:
    image: mongo:5-focal
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    env_file: .env

volumes:
  mongo_data:
