version: "3.9"

services:
  goth:
    build: .
    image: ghcr.io/alubhorta/goth
    ports:
      - 3333:3333
    restart: unless-stopped
    env_file: .prod.env
  mongodb:
    image: mongo:5-focal
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    env_file: .mongo.env
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
